import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="py-2 bg-pink-600 text-center text-3xl flex items-center justify-between px-4">
          <p>This is from ROOT layout</p>
          <div className="flex justify-center gap-4 py-2 text-base">
            <Link href="/todo">Todo</Link> <Link href="/about">About</Link>
            <Link href="/users">Users</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
